spring:
  application:
    name: word-query-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eager-load:
    enabled: true
#hystrix:
#  metrics:
#    enabled:
#      command:
#          default:
#            execution:
#              isolation:
#                strategy: THREAD
#                thread:
#                  timeoutInMilliseconds: 10000
management:
  endpoint:
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream","info","health"]
      base-path: /actuator
#        web:
#              exposure:
#                include: hystrix.stream
#              base-path: /
hystrix:
  metrics:
    enabled: true



